line_length: 150

enabled_rules:
 - vertical_whitespace_opening_braces
 - vertical_whitespace_closing_braces

disabled_rules:
 - todo

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
